[project]
name = "os-data-fetcher"
version = "0.1.0"
description = "Rapid Street Assessments (RSAs) are designed to quickly retrieve comprehensive information about streets and the surrounding area."
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
